# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('communication_type', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ControllerType',
            fields=[
                ('controller_type', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('communication', models.ManyToManyField(to='plc_org.CommunicationType')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('equip_num', models.IntegerField()),
                ('equipment_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_point_name', models.CharField(max_length=32)),
                ('tag_name', models.CharField(max_length=255)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plc_org.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('point_type', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_count', models.IntegerField()),
                ('rack_location', models.IntegerField()),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_org.Controller')),
                ('point_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plc_org.PointType')),
            ],
        ),
        migrations.CreateModel(
            name='Workcell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workcell', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_org.Department')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='point_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plc_org.PointType'),
        ),
        migrations.AddField(
            model_name='point',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plc_org.Rack'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='workcell',
            field=models.ManyToManyField(to='plc_org.Workcell'),
        ),
        migrations.AddField(
            model_name='controller',
            name='controller_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plc_org.ControllerType'),
        ),
        migrations.AddField(
            model_name='controller',
            name='primary_workcell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plc_org.Workcell'),
        ),
    ]
