# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc_org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=16),
            preserve_default=False,
        ),
    ]
