# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc_org', '0002_controller_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
    ]
